### PR TITLE
Add primitives tutorials ikkoham

### PR DESCRIPTION
**Pull request by mrvee-qC-bee**
### Summary
- Update primitive selection section

### CODE REVIEW

**Comment by ikkoham** [comment]
Could you make a PR to add-primitives-tutorials instead of master?

**Comment by mrvee-qC-bee** [comment]
Done!

**Review by ikkoham — APPROVED** [review]
LGTM!

**Comment by tula3and** [comment]
LGTM! Especially the chart looks amazing! 🌟 Thank you @mrvee-qC-bee @ikkoham

**Pull request merged**
